name: "ci"

on:
  push:
    branches-ignore: [ main ]

concurrency:
  group: "ci-${{ github.ref }}"
  cancel-in-progress: true

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

#region Setup

    - uses: actions/checkout@v3

#endregion

#region Lint all XML files

    - uses: tecolicom/actions-use-apt-tools@v1
      with:
        tools: libxml2-utils
    - uses: tj-actions/glob@v17
      id: glob
      with:
        files: "**/*.xml"
    - run: xmllint --noout ${{ steps.glob.outputs.paths }}

#endregion

#region Upload artifact

    - id: get-short-sha
      run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - uses: actions/upload-artifact@v3
      with:
        name: "${{ vars.MOD_NAME }}-${{ steps.get-short-sha.outputs.short_sha }}"
        path: |
          *
          !.*

#endregion
