name: '[PR] Require Label'

env:
  TYPE_LABELS: 'chore, bug, enhancement, feature'

on:
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]
    branches: [ main ]

jobs:

  require-label:

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:

    - id: get-type-label
      uses: mheap/github-action-required-labels@v5
      with:
        labels: ${{ env.TYPE_LABELS }}
        mode: exactly
        count: 1
        add_comment: true
        message: "This pull request cannot be merged because {{ errorString }} {{ count }} of `{{ provided }}` is required."
